const TestingSessionSchema = new Schema(
  {
    /* -------------------------
       Core Identity
    -------------------------- */
    title: {
      type: String,
      required: true,
    },

    description: {
      type: String,
    },

    coverImage: {
      type: String, // URL or storage key
    },

    /* -------------------------
       Ownership & Context
    -------------------------- */
    teamId: {
      type: Schema.Types.ObjectId,
      ref: 'Team',
      required: true,
    },

    triggeredBy: {
      type: Schema.Types.ObjectId,
      ref: 'Employee',
      required: true,
    },

    /* -------------------------
       Scope Definition
    -------------------------- */
    scope: {
      inScope: {
        type: [String], // e.g. ["Login", "Signup", "Payments"]
        default: [],
      },
      outOfScope: {
        type: [String],
        default: [],
      },
    },

    /* -------------------------
       Time & Duration
    -------------------------- */
    startedAt: {
      type: Date,
      required: true,
    },

    endedAt: {
      type: Date,
    },

    duration: {
      from: {
        type: String, // e.g. "10:00"
      },
      to: {
        type: String, // e.g. "23:00"
      },
    },

    /* -------------------------
       Session Status
    -------------------------- */
    status: {
      type: String,
      enum: ['planned', 'active', 'completed', 'archived'],
      default: 'planned',
    },

    /* -------------------------
       Target Platforms
    -------------------------- */
    targetPlatforms: {
      type: [String],
      enum: ['android', 'ios', 'windows', 'macOS'],
      default: [],
    },

    /* -------------------------
       Build Details
    -------------------------- */
    builds: [
      {
        platform: {
          type: String,
          enum: ['android', 'ios', 'web'],
          required: true,
        },

        buildNumber: {
          type: String,
          required: true,
        },

        buildUrl: {
          type: String,
          required: true,
        },

        qrCodeUrl: {
          type: String, // generated by backend
        },
      },
    ],

    /* -------------------------
       Team Member Selection
    -------------------------- */
    participantMode: {
      type: String,
      enum: ['all', 'custom'],
      default: 'all',
    },

    participants: [
      {
        type: Schema.Types.ObjectId,
        ref: 'TeamMember',
      },
    ],

    /* -------------------------
       Archival
    -------------------------- */
    archivedAt: {
      type: Date,
    },
  },
  { timestamps: true },
)
